- hosts: localhost
  connection: local
  become: true

  #CJP pre_tasks:
    #CJP - name: Clean repo data
      #CJP command: dnf clean all
      #CJP args:
        #CJP warn: no
    #CJP - name: Rebuild the cache
      #CJP command: dnf makecache
      #CJP args:
        #CJP warn: no
        
  tasks:
    - include: tasks/packages1.yml
    - include: tasks/repo_enable.yml
    - include: tasks/packages2.yml
    - include: tasks/users.yml
    - include: tasks/cron.yml
    - include: tasks/vnc_setup.yml
    #CJP - include: tasks/boinc.yml
