- name: Create Admin user
  user:
    name: admin
    system: yes
    local: yes
    password: $6$3x4QOzcRQv8Tlt1T$OUx.rEP/PSk3xzJBC8QP.FpNRQTlTBQlsZYAwDWGt8BMHbnZTivkQd7kHeCdWBZZthIDuu1UlDHcVY6zDfiMo0
    comment: Administration account
    group: wheel
    uid:700
    expires: -1

- name: Create Ansible user
  user:
    name: ansible
    system: yes
    local: yes
    password: !
    comment: Ansible account
    uid:701
    expires: -1

- name: Create Ebesucher user
  user:
    name: ebesucher
    system: yes
    local: yes
    password: !
    comment: eBesucher user
    uid:702
    expires: -1

- name: Create HitLeap user
  user:
    name: hitleap
    system: yes
    local: yes
    password: !
    comment: HitLeap user
    uid:703
    expires: -1

- name: Create HoneyGain user
  user:
    name: honeygain
    system: yes
    local: yes
    password: !
    comment: HoneyGain user
    uid:704
    expires: -1

- name: Create Monero user
  user:
    name: monero
    system: yes
    local: yes
    password: !
    comment: Monero user
    uid:705
    expires: -1

- name: Copy in Ansible sudoers entry
  copy:
    src: files/sudoers_main
    dest: /etc/sudoers
    owner: root
    group: root
    mode: 0440

- name: Copy in Ansible sudoers entry
  copy:
    src: files/sudoers_ansible
    dest: /etc/sudoers.d/ansible
    owner: root
    group: root
    mode: 0440

- name: Expire the Admin user password to force a reset
  command: /usr/bin/passwd -expire admin
  args:
    warn: no
