- name: "Create Admin user"
  user:
    name: admin
    system: yes
    local: yes
    password: "$6$3x4QOzcRQv8Tlt1T$OUx.rEP/PSk3xzJBC8QP.FpNRQTlTBQlsZYAwDWGt8BMHbnZTivkQd7kHeCdWBZZthIDuu1UlDHcVY6zDfiMo0"
    comment: Administration account
    uid: 700

- name: "Create Ansible user"
  user:
    name: ansible
    system: yes
    local: yes
    password: !
    comment: Ansible account
    uid: 701

- name: "Copy in Ansible sudoers entry"
  copy:
    src: files/sudoers_main
    dest: /etc/sudoers
    owner: root
    group: root
    mode: 0440

- name: "Copy in Ansible sudoers entry"
  copy:
    src: files/sudoers_ansible
    dest: /etc/sudoers.d/ansible
    owner: root
    group: root
    mode: 0440

- name: "Set admin user to never expire"
  command: "/usr/bin/chage -E -1 admin"
  args:
    warn: no

- name: "Set admin user inactivity to -1"
  command: "/usr/bin/chage -I -1 admin"
  args:
    warn: no

- name: "Set admin user maxdays to -1"
  command: "/usr/bin/chage -M -1 admin"
  args:
    warn: no

- name: "Set admin user mindays to -1"
  command: "/usr/bin/chage -m -1 admin"
  args:
    warn: no

- name: "Add admin to the wheel group"
  command: "/usr/sbin/usermod -G wheel admin"
  args:
    warn: no
