- name: Create Ansible user
  user:
    name: ansible
    system: yes

- name: Create Ebesucher user
  user:
    name: ebesucher

- name: Create HitLeap user
  user:
    name: hitleap

- name: Create HoneyGain user
  user:
    name: honeygain
    system: yes

- name: Create Ansible user
  user:
    name: ansible
    system: yes

- name: Copy in Ansible sudoers entry
  copy:
    src: files/sudoers_main
    dest: /etc/sudoers
    owner: root
    group: root
    mode: 0440

- name: Copy in Ansible sudoers entry
  copy:
    src: files/sudoers_ansible
    dest: /etc/sudoers.d/ansible
    owner: root
    group: root
    mode: 0440
